In [7]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix
dataset =pd.read_csv("C:/Users/Stephen/Downloads/iris.csv")
X = dataset.drop(["class"], axis=1) 
Y = dataset["class"] 
from sklearn import tree
DT_model= tree.DecisionTreeClassifier()
DT_model.fit(X, Y)
y_pred = DT_model.predict(X)
print(confusion_matrix(Y,y_pred))
print('準確度：' + str(accuracy_score(Y, y_pred)))


[[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]
準確度：1.0


In [8]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix
dataset =pd.read_csv("C:/Users/Stephen/Downloads/iris.csv")
X = dataset.drop(["class"], axis=1) 
Y = dataset["class"] 
from sklearn.neural_network import MLPClassifier
NN_model = MLPClassifier()
NN_model.fit(X, Y)
y_pred = NN_model.predict(X)
print(confusion_matrix(Y,y_pred))
print('準確度：' + str(accuracy_score(Y, y_pred)))


[[50  0  0]
 [ 0 47  3]
 [ 0  0 50]]
準確度：0.98


C:\Users\Stephen\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [11]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix
dataset =pd.read_csv("C:/Users/Stephen/Downloads/iris.csv")
X = dataset.drop(["class"], axis=1) 
Y = dataset["class"] 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X,Y)
y_pred = knn.predict(X)
print(confusion_matrix(Y,y_pred))
print('準確度：' + str(accuracy_score(Y, y_pred)))

[[50  0  0]
 [ 0 48  2]
 [ 0  2 48]]
準確度：0.9733333333333334


In [12]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix
dataset =pd.read_csv("C:/Users/Stephen/Downloads/iris.csv")
X = dataset.drop(["class"], axis=1) 
Y = dataset["class"] 
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(X, Y)
y_pred = LR.predict(X)
print(confusion_matrix(Y,y_pred))
print('準確度：' + str(accuracy_score(Y, y_pred)))

[[50  0  0]
 [ 0 47  3]
 [ 0  1 49]]
準確度：0.9733333333333334


In [13]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix
dataset =pd.read_csv("C:/Users/Stephen/Downloads/iris.csv")
X = dataset.drop(["class"], axis=1) 
Y = dataset["class"] 
from sklearn.naive_bayes import GaussianNB
NB_model =GaussianNB()
NB_model.fit(X, Y)
y_pred = NB_model.predict(X)
print(confusion_matrix(Y,y_pred))
print('準確度：' + str(accuracy_score(Y, y_pred)))

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
準確度：0.96


In [14]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix
dataset =pd.read_csv("C:/Users/Stephen/Downloads/iris.csv")
X = dataset.drop(["class"], axis=1) 
Y = dataset["class"] 
from sklearn.svm import SVC
SVM_model =SVC()
SVM_model.fit(X, Y)
y_pred = SVM_model.predict(X)
print(confusion_matrix(Y,y_pred))
print('準確度：' + str(accuracy_score(Y, y_pred)))

[[50  0  0]
 [ 0 48  2]
 [ 0  2 48]]
準確度：0.9733333333333334
